<a href="https://colab.research.google.com/github/bnanik/Shared_Task_SemEval2023/blob/main/ShareTask_NB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
%cd /content/drive/My Drive

/content/drive/My Drive


In [ ]:
import pandas as pd

df=pd.read_csv("train_all_tasks.csv")

In [ ]:
df["text_lower"] = df["text"].str.lower()
df.head()

rewire_id  \
0   sexism2022_english-7358   
1   sexism2022_english-2367   
2   sexism2022_english-3073   
3  sexism2022_english-14895   
4   sexism2022_english-4118   

                                                text label_sexist  \
0              Damn, this writing was pretty chaotic   not sexist   
1  Yeah, and apparently a bunch of misogynistic v...   not sexist   
2       How the FUCK is this woman still an MP!!!???   not sexist   
3  Understand. Know you're right. At same time I ...   not sexist   
4     Surprized they didn't stop and rape some women   not sexist   

  label_category label_vector  \
0           none         none   
1           none         none   
2           none         none   
3           none         none   
4           none         none   

                                          text_lower  
0              damn, this writing was pretty chaotic  
1  yeah, and apparently a bunch of misogynistic v...  
2       how the fuck is this woman still an mp!!!???  
3  understand. know you're right. at same time i ...  
4     surprized they didn't stop and rape some women

In [ ]:
df['label_sexist'].value_counts()

not sexist    10602
sexist         3398
Name: label_sexist, dtype: int64

In [ ]:
df['length'] = df['text_lower'].apply(lambda x: len(x))
df.drop(["text", "label_category","label_vector","rewire_id"], axis=1, inplace=True)
df.head()

label_sexist                                         text_lower  length
0   not sexist              damn, this writing was pretty chaotic      37
1   not sexist  yeah, and apparently a bunch of misogynistic v...      99
2   not sexist       how the fuck is this woman still an mp!!!???      44
3   not sexist  understand. know you're right. at same time i ...     137
4   not sexist     surprized they didn't stop and rape some women      46

In [ ]:
!pip install nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import nltk

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
from nltk import word_tokenize
import re

In [ ]:
import re #used for Regular Expression 
import string
from collections import defaultdict

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [ ]:
PUNCT_TO_REMOVE = string.punctuation
def remove_punctuation(text_lower):
    """custom function to remove the punctuation"""
    return text_lower.translate(str.maketrans('', '', PUNCT_TO_REMOVE))

df["text_wo_punct"] = df["text_lower"].apply(lambda text_lower: remove_punctuation(text_lower))
df.head()

label_sexist                                         text_lower  length  \
0   not sexist              damn, this writing was pretty chaotic      37   
1   not sexist  yeah, and apparently a bunch of misogynistic v...      99   
2   not sexist       how the fuck is this woman still an mp!!!???      44   
3   not sexist  understand. know you're right. at same time i ...     137   
4   not sexist     surprized they didn't stop and rape some women      46   

                                       text_wo_punct  
0               damn this writing was pretty chaotic  
1  yeah and apparently a bunch of misogynistic vi...  
2             how the fuck is this woman still an mp  
3  understand know youre right at same time i kno...  
4      surprized they didnt stop and rape some women

In [ ]:
from nltk.corpus import stopwords
", ".join(stopwords.words('english'))

"i, me, my, myself, we, our, ours, ourselves, you, you're, you've, you'll, you'd, your, yours, yourself, yourselves, he, him, his, himself, she, she's, her, hers, herself, it, it's, its, itself, they, them, their, theirs, themselves, what, which, who, whom, this, that, that'll, these, those, am, is, are, was, were, be, been, being, have, has, had, having, do, does, did, doing, a, an, the, and, but, if, or, because, as, until, while, of, at, by, for, with, about, against, between, into, through, during, before, after, above, below, to, from, up, down, in, out, on, off, over, under, again, further, then, once, here, there, when, where, why, how, all, any, both, each, few, more, most, other, some, such, no, nor, not, only, own, same, so, than, too, very, s, t, can, will, just, don, don't, should, should've, now, d, ll, m, o, re, ve, y, ain, aren, aren't, couldn, couldn't, didn, didn't, doesn, doesn't, hadn, hadn't, hasn, hasn't, haven, haven't, isn, isn't, ma, mightn, mightn't, mustn, mus

In [ ]:
STOPWORDS = set(stopwords.words('english'))
def remove_stopwords(text):
    """custom function to remove the stopwords"""
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])

df["text_wo_stop"] = df["text_wo_punct"].apply(lambda text: remove_stopwords(text))
df.head()

label_sexist                                         text_lower  length  \
0   not sexist              damn, this writing was pretty chaotic      37   
1   not sexist  yeah, and apparently a bunch of misogynistic v...      99   
2   not sexist       how the fuck is this woman still an mp!!!???      44   
3   not sexist  understand. know you're right. at same time i ...     137   
4   not sexist     surprized they didn't stop and rape some women      46   

                                       text_wo_punct  \
0               damn this writing was pretty chaotic   
1  yeah and apparently a bunch of misogynistic vi...   
2             how the fuck is this woman still an mp   
3  understand know youre right at same time i kno...   
4      surprized they didnt stop and rape some women   

                                        text_wo_stop  
0                        damn writing pretty chaotic  
1  yeah apparently bunch misogynistic virgins one...  
2                                fuck woman still mp  
3  understand know youre right time know isnt eno...  
4                    surprized didnt stop rape women

In [ ]:
def remove_extra_white_spaces(text):
    single_char_pattern = r'\s+[a-zA-Z]\s+'
    without_sc = re.sub(pattern=single_char_pattern, repl=" ", string=text)
    return without_sc

In [ ]:
df['text'] = df['text_wo_stop'].apply(lambda x: remove_extra_white_spaces(x))

In [ ]:
def lemmatizing(text):
    lemmatizer = WordNetLemmatizer()
    tokens = word_tokenize(text)
    for i in range(len(tokens)):
        lemma_word = lemmatizer.lemmatize(tokens[i])
        tokens[i] = lemma_word
    return " ".join(tokens)

In [ ]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


True

In [ ]:
df['textLemma'] = df['text'].apply(lambda x: lemmatizing(x))
df.head()

label_sexist                                         text_lower  length  \
0   not sexist              damn, this writing was pretty chaotic      37   
1   not sexist  yeah, and apparently a bunch of misogynistic v...      99   
2   not sexist       how the fuck is this woman still an mp!!!???      44   
3   not sexist  understand. know you're right. at same time i ...     137   
4   not sexist     surprized they didn't stop and rape some women      46   

                                       text_wo_punct  \
0               damn this writing was pretty chaotic   
1  yeah and apparently a bunch of misogynistic vi...   
2             how the fuck is this woman still an mp   
3  understand know youre right at same time i kno...   
4      surprized they didnt stop and rape some women   

                                        text_wo_stop  \
0                        damn writing pretty chaotic   
1  yeah apparently bunch misogynistic virgins one...   
2                                fuck woman still mp   
3  understand know youre right time know isnt eno...   
4                    surprized didnt stop rape women   

                                                text  \
0                        damn writing pretty chaotic   
1  yeah apparently bunch misogynistic virgins one...   
2                                fuck woman still mp   
3  understand know youre right time know isnt eno...   
4                    surprized didnt stop rape women   

                                           textLemma  
0                        damn writing pretty chaotic  
1  yeah apparently bunch misogynistic virgin one ...  
2                                fuck woman still mp  
3  understand know youre right time know isnt eno...  
4                    surprized didnt stop rape woman

In [ ]:
df.drop(["text_wo_stop","text"], axis=1, inplace=True)

In [ ]:
import re

def remove_URL(text):
  url=re.compile(r"https?://\S+|www.\.\S+")
  return url.sub(r"",text)

def remove_html(text):
  html=re.compile(r"<.*?>")
  return html.sub(r"",text)

def remove_emoji(string):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', string)

In [ ]:
import nltk
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [ ]:
df["text_removeU"] = df["textLemma"].apply(lambda text: remove_URL(text))
df["text_removeH"] = df["text_removeU"].apply(lambda text: remove_html(text))
df["text_clean_final"] = df["text_removeH"].apply(lambda text: remove_emoji(text))

In [ ]:
df['length_after_cleaning'] = df['text_clean_final'].apply(lambda x: len(x))
df.head()

label_sexist                                         text_lower  length  \
0   not sexist              damn, this writing was pretty chaotic      37   
1   not sexist  yeah, and apparently a bunch of misogynistic v...      99   
2   not sexist       how the fuck is this woman still an mp!!!???      44   
3   not sexist  understand. know you're right. at same time i ...     137   
4   not sexist     surprized they didn't stop and rape some women      46   

                                       text_wo_punct  \
0               damn this writing was pretty chaotic   
1  yeah and apparently a bunch of misogynistic vi...   
2             how the fuck is this woman still an mp   
3  understand know youre right at same time i kno...   
4      surprized they didnt stop and rape some women   

                                           textLemma  \
0                        damn writing pretty chaotic   
1  yeah apparently bunch misogynistic virgin one ...   
2                                fuck woman still mp   
3  understand know youre right time know isnt eno...   
4                    surprized didnt stop rape woman   

                                        text_removeU  \
0                        damn writing pretty chaotic   
1  yeah apparently bunch misogynistic virgin one ...   
2                                fuck woman still mp   
3  understand know youre right time know isnt eno...   
4                    surprized didnt stop rape woman   

                                        text_removeH  \
0                        damn writing pretty chaotic   
1  yeah apparently bunch misogynistic virgin one ...   
2                                fuck woman still mp   
3  understand know youre right time know isnt eno...   
4                    surprized didnt stop rape woman   

                                    text_clean_final  length_after_cleaning  
0                        damn writing pretty chaotic                     27  
1  yeah apparently bunch misogynistic virgin one ...                     73  
2                                fuck woman still mp                     19  
3  understand know youre right time know isnt eno...                     94  
4                    surprized didnt stop rape woman                     31

In [ ]:
df.drop(["text_wo_punct","textLemma","text_removeU","text_removeH"], axis=1, inplace=True)


In [ ]:
df.head()

label_sexist                                         text_lower  length  \
0   not sexist              damn, this writing was pretty chaotic      37   
1   not sexist  yeah, and apparently a bunch of misogynistic v...      99   
2   not sexist       how the fuck is this woman still an mp!!!???      44   
3   not sexist  understand. know you're right. at same time i ...     137   
4   not sexist     surprized they didn't stop and rape some women      46   

                                    text_clean_final  length_after_cleaning  
0                        damn writing pretty chaotic                     27  
1  yeah apparently bunch misogynistic virgin one ...                     73  
2                                fuck woman still mp                     19  
3  understand know youre right time know isnt eno...                     94  
4                    surprized didnt stop rape woman                     31

In [ ]:
df.to_csv("clean_data_v2.csv")

In [ ]:
label_map = {
    'not sexist': 0,
    'sexist': 1,
}

In [ ]:
df['label'] = df['label_sexist'].map(label_map)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tf_wb= TfidfVectorizer()

In [ ]:
X_tf = tf_wb.fit_transform(df['text_clean_final'])

In [ ]:
import numpy as np
X_tf = X_tf.toarray()
print(X_tf)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train_tf, X_test_tf, y_train_tf, y_test_tf = train_test_split(X_tf, df['label'].values, test_size=0.3)

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
NB = GaussianNB()

In [ ]:
NB.fit(X_train_tf, y_train_tf)

GaussianNB()

In [ ]:
NB_pred= NB.predict(X_test_tf)
print(NB_pred)

[1 1 0 ... 1 1 1]


In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
print(accuracy_score(y_test_tf, NB_pred))

0.5357142857142857


In [ ]:
!pip install imbalanced-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from imblearn.over_sampling import RandomOverSampler

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df['text_clean_final'], df['label'].values, test_size=0.30)

In [ ]:
from collections import Counter

In [ ]:
Counter(y_train)

Counter({0: 7376, 1: 2424})

In [ ]:
Counter({0: 3371, 1: 529})

Counter({0: 3371, 1: 529})

In [ ]:
vectorizer = TfidfVectorizer()
vectorizer.fit(X_train)

TfidfVectorizer()

In [ ]:
X_train_tf = vectorizer.transform(X_train)

In [ ]:
X_train_tf = X_train_tf.toarray()

In [ ]:
X_test_tf = vectorizer.transform(X_test)
X_test_tf = X_test_tf.toarray()

In [ ]:
ROS = RandomOverSampler(sampling_strategy=1)

In [ ]:
X_train_ros, y_train_ros = ROS.fit_resample(X_train_tf, y_train)

In [ ]:
Counter(y_train_ros)

Counter({0: 7376, 1: 7376})

In [ ]:
Counter({0: 3371, 1: 3371})

Counter({0: 3371, 1: 3371})

In [ ]:
nb = GaussianNB()

In [ ]:
nb.fit(X_train_ros, y_train_ros)

GaussianNB()

In [ ]:
y_preds = nb.predict(X_test_tf)
print(y_preds)

[0 0 1 ... 1 0 0]


In [ ]:
print(accuracy_score(y_test, y_preds))

0.535


In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_preds)

print('Confusion matrix\n\n', cm)

Confusion matrix

 [[1727 1499]
 [ 454  520]]


In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.79      0.54      0.64      3226
           1       0.26      0.53      0.35       974

    accuracy                           0.54      4200
   macro avg       0.52      0.53      0.49      4200
weighted avg       0.67      0.54      0.57      4200



In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, np.zeros_like(y_test)))

              precision    recall  f1-score   support

           0       0.77      1.00      0.87      3226
           1       0.00      0.00      0.00       974

    accuracy                           0.77      4200
   macro avg       0.38      0.50      0.43      4200
weighted avg       0.59      0.77      0.67      4200



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
