In [4]:
!py -m pip install sklearn numpy transformers datasets 
#!py -m pip install jsonlib
#!py -m pip install torch

  Using cached datasets-2.7.1-py3-none-any.whl (451 kB)


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the 'C:\Users\12Build\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [2]:
import pandas as pd

In [ ]:
def read_data(self,filename):
        sentences = []
        with open(filename, 'r', encoding='UTF-8') as f:
            sentence = []
            for line in f:
                line = line.strip()
                if len(line) != 0:
                    sentence.append((line.split(',')[4], line.split(',')[1]))   # getting text and label columns
                elif len(sentence) != 0:
                    sentences.append(sentence)
                    sentence = []
        self.tags = list(set(word_label[1] for sent in sentences for word_label in sent))
        return sentences 



In [33]:
label_to_ids = {'not sexist':0,'sexist':1}
st_file="../Data/clean_data_v2.csv"
data=pd.read_csv(st_file)
data['label_sexist']=data['label_sexist'].map(label_to_ids)
data=data.filter(items=["text_clean_final","label_sexist"],axis=1)
data.columns=['text','label']



['damn writing pretty chaotic',
 'yeah apparently bunch misogynistic virgin one turn gay woman straight lol',
 'fuck woman still mp',
 'understand know youre right time know isnt enough money world induce beastly female equivalent',
 'surprized didnt stop rape woman',
 'yeah order keep benefit good tommorow told could try',
 'hahaha wish would live truth cut shit wouldnt worry mf society',
 'head mod said talked made post won ’ t tell anyone talked say it ’ s “ classified ” one freaking unlike mod',
 'inside wallet cash bank card credit card debit card inside matter femoids',
 'definitely didn ’ t go much detail happened put stop dry humping got involved top put stop thing went',
 'oh shit clearly know big 5 trait deflect use magic rp word',
 'get initial chance attractive woman flock see woman flocking penguin hesitating jump iceberg',
 'first word president would ban sport ball forever one play sport professionally amateur accolade compensation shekel',
 'sometimes im girl reason hea

In [34]:
data['label'].unique()

array([0, 1], dtype=int64)

In [35]:
data['text'].values

array(['damn writing pretty chaotic',
       'yeah apparently bunch misogynistic virgin one turn gay woman straight lol',
       'fuck woman still mp', ...,
       'lol imagine would simps like “ she doesn ’ t deserve ugly guy ” jfl',
       'girl go date dont kiss first date dont text back first date',
       'incel girlfriend fuck anyone say kissed legit 710 girl fuck looking fag'],
      dtype=object)

In [7]:
from torch import nn
import torch
m = nn.Sigmoid()
arr=[0.7311, 0.5000, 0.7311, 0.7311, 0.5000]
input = torch.tensor(arr) #torch.randn(2)
print(input)
print(m(input))

tensor([0.7311, 0.5000, 0.7311, 0.7311, 0.5000])
tensor([0.6750, 0.6225, 0.6750, 0.6750, 0.6225])
